/*
 * keymap.c
 *
 * Created: 2/01/2018 4:15:02 PM
 *  Author: cong
 */ 

 #include <asf.h>
 #include "keycode.h"
 #include "action.h"

 const action_t actionmaps[][MATRIX_ROWS][MATRIX_COLS] = {
	{
	{KC_GRAVE,KC_F1,KC_F2,KC_5,KC_6,KC_EQUAL,KC_F8,KC_MINUS,KC_F9,KC_NO,KC_HOME,KC_DELETE,KC_NO,KC_NO,KC_NO,KC_LCTRL},
	{KC_1,KC_2,KC_3,KC_4,KC_7,KC_8,KC_9,KC_0,KC_F10,KC_F12,KC_F11,KC_INSERT,KC_END,KC_NO,KC_NO,KC_NO},
	{KC_Q,KC_W,KC_E,KC_R,KC_U,KC_I,KC_O,KC_P,KC_NO,KC_NO,KC_AUDIO_VOL_UP,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO},
	{KC_TAB,KC_CAPSLOCK,KC_F3,KC_T,KC_Y,KC_RBRACKET,KC_F7,KC_LBRACKET,KC_BSPACE,KC_LGUI,KC_AUDIO_VOL_DOWN,KC_NO,KC_NO,KC_NO,KC_LSHIFT,KC_NO},
	{KC_A,KC_S,KC_D,KC_F,KC_J,KC_K,KC_L,KC_SCOLON,KC_BSLASH,KC_NO,KC_AUDIO_MUTE,KC_PSCREEN,KC_NO,KC_NO,KC_NO,KC_NO},
	{KC_ESCAPE,KC_NO,KC_F4,KC_G,KC_H,KC_F6,KC_NO,KC_QUOTE,KC_F5,KC_NO,KC_NO,KC_NO,KC_UP,KC_LALT,KC_NO,KC_NO},
	{KC_Z,KC_X,KC_C,KC_V,KC_M,KC_COMMA,KC_DOT,KC_NO,KC_ENTER,KC_NO,91,KC_PGUP,KC_NO,KC_NO,KC_RSHIFT,KC_NO},
	{KC_NO,KC_NO,KC_NO,KC_B,KC_N,KC_NO,KC_NO,KC_SLASH,KC_SPACE,KC_RIGHT,KC_DOWN,KC_PGDOWN,KC_LEFT,KC_RALT,KC_NO,KC_RCTRL}
	}
 };